node {
    env.BUILD_DIR = "/root/jenkins/build_workspace"
    env.MODULE = "huiba-gaia-gateway/huiba-gaia-gateway-server"
    env.HOST = "hbgaia-gateway.emon.vip"
    env.NS = "drill"
    env.DEPLOY_YAML = "k8s-deploy-drill.yaml"

    stage('Preparation') {
        sh 'printenv'
        // git 'git@github.com:EmonCodingBackEnd/backend-devops-learning.git'
        // git branch: "${params.BRANCH}", url: 'git@github.com:EmonCodingBackEnd/backend-devops-learning.git'
        git branch: "develop", url: 'http://git.ishanshan.com/huiba-backend/huiba-gaia.git'
    }

    stage('Maven Build') {
        sh "mvn -pl ${MODULE} -am clean package -Dmaven.test.skip=true"
    }

    stage('Build Image') {
        sh "/root/jenkins/script/build-image-web.sh"
    }

    stage('Deploy') {
        sh "/root/jenkins/script/deploy.sh"
    }
}