spring:
  application:
    name: fullstack-ware
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://repo.emon.vip:3306/gulimall_wms?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.10.1:8848
  config:
    import:
      - nacos:fullstack-ware.properties?refresh=true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 11000
logging:
  level:
    com.coding.fullstack.ware.dao: debug
