spring:
  application:
    name: fullstack-product
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://repo.emon.vip:3306/gulimall_pms?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: repo.emon.vip:8848
      config:
        server-addr: repo.emon.vip:8848
  config:
    import:
      - nacos:fullstack-product.properties?refresh=true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: repo.emon.vip
    port: 6379
    password: redis123
    database: 0
    timeout: 3000ms
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: 'fullstack:product:'
      use-key-prefix: true
      cache-null-values: true # 缓存空值，避免缓存穿透
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000
  servlet:
    session:
      timeout: 10m

logging:
  level:
    com.coding.fullstack.product.dao: error
thread:
  pool:
    core-size: 10
    max-size: 200
    keep-alive-time: 10
    queue-size: 100000
