spring:
  application:
    name: fullstack-search
  cloud:
    nacos:
      discovery:
        server-addr: repo.emon.vip:8848
      config:
        server-addr: repo.emon.vip:8848
  config:
    import:
      - nacos:fullstack-product.properties?refresh=true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: repo.emon.vip
    port: 6379
    password: redis123
    database: 0
    timeout: 3000ms
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save

server:
  port: 12000
  servlet:
    session:
      timeout: 10m